# ============================================================
# Author:       Lin Lin
# Date:         2026-09-04
# ============================================================

import socket
import struct
import time
import csv
from datetime import datetime

import numpy as np


# ============================================================
# CONFIG
# ============================================================

UDP_IP = "0.0.0.0"
UDP_PORT = 6060

ANGLE_SCALE = 4194304.0

# Raw SICK UDP datagram header
DATAGRAM_HEADER_SIZE = 24

# Binary PLY can be loaded directly by Three.js PLYLoader.  Increase this
# value (for example to 2, 5 or 10) if the browser should receive fewer points.
PLY_EXPORT_STRIDE = 1

# Matplotlib is now only an optional fallback preview; PLY export is always on.
GENERATE_MATPLOTLIB_PREVIEW = False


# ============================================================
# STORAGE
# ============================================================

fragments = {}

all_x = []
all_y = []
all_time = []
all_rssi = []

scan_count = 0
packet_count = 0


timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

raw_filename = f"sick_raw_{timestamp}.bin"
csv_filename = f"sick_points_{timestamp}.csv"
png_filename = f"sick_pointcloud_{timestamp}.png"
ply_filename = f"sick_pointcloud_{timestamp}.ply"


raw_file = open(raw_filename, "wb")
csv_file = open(csv_filename, "w", newline="")

csv_writer = csv.writer(csv_file)

csv_writer.writerow([
    "scan_number",
    "time_s",
    "beam",
    "angle_deg",
    "distance_mm",
    "x_m",
    "y_m",
    "rssi",
    "status"
])


# ============================================================
# SAVE RAW UDP
# ============================================================

def save_raw_packet(data):
    """
    Store:
        timestamp_ns : uint64
        length       : uint32
        raw payload
    """

    timestamp_ns = time.time_ns()

    raw_file.write(
        struct.pack("<QI", timestamp_ns, len(data))
    )

    raw_file.write(data)


# ============================================================
# EXPORT BINARY PLY FOR THREE.JS
# ============================================================

def save_binary_ply(filename, x, y, time_s, rssi):
    """Save X/Y/Time points as compact binary PLY vertices.

    Besides standard RGB vertex colors, the original RSSI byte is retained as
    a custom property so a Three.js shader can use it later if desired.
    """

    point_count = len(x)
    vertices = np.empty(
        point_count,
        dtype=np.dtype([
            ("x", "<f4"),
            ("y", "<f4"),
            ("z", "<f4"),
            ("red", "u1"),
            ("green", "u1"),
            ("blue", "u1"),
            ("rssi", "u1"),
        ])
    )

    vertices["x"] = x
    vertices["y"] = y
    vertices["z"] = time_s

    # Fast blue -> cyan/yellow -> red mapping, calculated without Matplotlib.
    intensity = rssi.astype(np.float32) / 255.0
    vertices["red"] = (
        np.clip(2.0 * intensity - 0.5, 0.0, 1.0) * 255
    ).astype(np.uint8)
    vertices["green"] = (
        np.clip(1.5 - 3.0 * np.abs(intensity - 0.5), 0.0, 1.0) * 255
    ).astype(np.uint8)
    vertices["blue"] = (
        np.clip(1.5 - 2.0 * intensity, 0.0, 1.0) * 255
    ).astype(np.uint8)
    vertices["rssi"] = rssi

    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment generated by pointcloud.py\n"
        "comment axes x=x_m y=y_m z=time_s\n"
        f"element vertex {point_count}\n"
        "property float x\n"
        "property float y\n"
        "property float z\n"
        "property uchar red\n"
        "property uchar green\n"
        "property uchar blue\n"
        "property uchar rssi\n"
        "end_header\n"
    ).encode("ascii")

    with open(filename, "wb") as ply_file:
        ply_file.write(header)
        vertices.tofile(ply_file)


# ============================================================
# REASSEMBLE SICK UDP FRAGMENTS
# ============================================================

def process_datagram(data):

    if len(data) < DATAGRAM_HEADER_SIZE:
        return None

    # microScan3 datagram marker
    if data[0:4] != b"MS3 ":
        return None

    # Measurement Data protocol
    if data[4:6] != b"MD":
        return None

    total_length = struct.unpack_from(
        "<I", data, 8
    )[0]

    identification = struct.unpack_from(
        "<I", data, 12
    )[0]

    fragment_offset = struct.unpack_from(
        "<I", data, 16
    )[0]

    payload = data[DATAGRAM_HEADER_SIZE:]

    # Create scan buffer
    if identification not in fragments:

        fragments[identification] = {
            "total_length": total_length,
            "parts": {}
        }

    scan = fragments[identification]

    scan["parts"][fragment_offset] = payload

    # Check whether fragments form a complete continuous block

    offsets = sorted(scan["parts"].keys())

    expected_offset = 0

    for offset in offsets:

        if offset != expected_offset:
            return None

        expected_offset += len(
            scan["parts"][offset]
        )

    if expected_offset < total_length:
        return None

    # Complete scan
    complete_data = bytearray()

    for offset in offsets:
        complete_data.extend(
            scan["parts"][offset]
        )

    complete_data = bytes(
        complete_data[:total_length]
    )

    del fragments[identification]

    return complete_data


# ============================================================
# PARSE COMPLETE SCAN
# ============================================================

def parse_scan(data):

    global scan_count

    # Data output header = 56 bytes
    if len(data) < 56:
        return

    # Use the local receive time as the time axis.  Every point in the same
    # scan gets the same timestamp, measured from the start of recording.
    scan_time_s = time.perf_counter() - start_time

    scan_number = struct.unpack_from(
        "<I", data, 20
    )[0]

    # Header offsets
    config_offset = struct.unpack_from(
        "<H", data, 36
    )[0]

    config_size = struct.unpack_from(
        "<H", data, 38
    )[0]

    measurement_offset = struct.unpack_from(
        "<H", data, 40
    )[0]

    measurement_size = struct.unpack_from(
        "<H", data, 42
    )[0]

    # --------------------------------------------------------
    # Configuration block
    # --------------------------------------------------------

    if config_offset == 0 or config_size == 0:

        print(
            "WARNING: Configuration block missing."
        )

        return

    factor = struct.unpack_from(
        "<H", data, config_offset
    )[0]

    config_beams = struct.unpack_from(
        "<H", data, config_offset + 2
    )[0]

    start_angle_raw = struct.unpack_from(
        "<i", data, config_offset + 8
    )[0]

    angular_resolution_raw = struct.unpack_from(
        "<i", data, config_offset + 12
    )[0]

    start_angle_deg = (
        start_angle_raw / ANGLE_SCALE
    )

    angular_resolution_deg = (
        angular_resolution_raw / ANGLE_SCALE
    )

    # --------------------------------------------------------
    # Measurement block
    # --------------------------------------------------------

    if measurement_offset == 0 or measurement_size == 0:

        print(
            "WARNING: Measurement block missing."
        )

        return

    number_of_beams = struct.unpack_from(
        "<I",
        data,
        measurement_offset
    )[0]

    # sanity check
    if number_of_beams > 10000:
        print(
            f"Invalid beam count: {number_of_beams}"
        )
        return

    valid_points = 0

    for i in range(number_of_beams):

        beam_offset = (
            measurement_offset
            + 4
            + i * 4
        )

        if beam_offset + 4 > len(data):
            break

        distance = struct.unpack_from(
            "<H",
            data,
            beam_offset
        )[0]

        rssi = data[
            beam_offset + 2
        ]

        status = data[
            beam_offset + 3
        ]

        # Status bit 0 = Valid
        valid = (status & 0x01) != 0

        # Status bit 1 = no reflected pulse
        no_reflection = (
            status & 0x02
        ) != 0

        if not valid:
            continue

        if no_reflection:
            continue

        if distance == 0:
            continue

        distance_mm = (
            distance * factor
        )

        angle_deg = (
            start_angle_deg
            + i * angular_resolution_deg
        )

        angle_rad = np.deg2rad(
            angle_deg
        )

        distance_m = (
            distance_mm / 1000.0
        )

        x = (
            distance_m
            * np.cos(angle_rad)
        )

        y = (
            distance_m
            * np.sin(angle_rad)
        )

        all_x.append(x)
        all_y.append(y)
        all_time.append(scan_time_s)
        all_rssi.append(rssi)

        csv_writer.writerow([
            scan_number,
            scan_time_s,
            i,
            angle_deg,
            distance_mm,
            x,
            y,
            rssi,
            status
        ])

        valid_points += 1

    scan_count += 1

    if scan_count % 10 == 0:

        print(
            f"Scans: {scan_count:6d} | "
            f"Beams: {number_of_beams:4d} | "
            f"Valid points: {valid_points:4d} | "
            f"Start: {start_angle_deg:8.3f} deg | "
            f"Resolution: {angular_resolution_deg:.4f} deg"
        )


# ============================================================
# MAIN
# ============================================================

sock = socket.socket(
    socket.AF_INET,
    socket.SOCK_DGRAM
)

# Larger receive buffer
sock.setsockopt(
    socket.SOL_SOCKET,
    socket.SO_RCVBUF,
    4 * 1024 * 1024
)

sock.bind(
    (UDP_IP, UDP_PORT)
)

print()
print("=" * 60)
print("SICK microScan3 Recorder")
print("=" * 60)

print(
    f"Listening on UDP port {UDP_PORT}"
)

print(
    "Recording started."
)

print(
    "Press Ctrl+C to STOP and generate point cloud."
)

print()

start_time = time.perf_counter()


try:

    while True:

        data, addr = sock.recvfrom(
            65535
        )

        packet_count += 1

        # Always preserve original packet
        save_raw_packet(data)

        complete_scan = process_datagram(
            data
        )

        if complete_scan is not None:

            parse_scan(
                complete_scan
            )


except KeyboardInterrupt:

    pass


finally:

    elapsed = time.perf_counter() - start_time

    sock.close()

    raw_file.close()
    csv_file.close()


# ============================================================
# RESULT
# ============================================================

print()
print("=" * 60)
print("Recording stopped")
print("=" * 60)

print(
    f"Duration     : {elapsed:.2f} sec"
)

print(
    f"UDP packets  : {packet_count}"
)

print(
    f"Scans        : {scan_count}"
)

print(
    f"Valid points : {len(all_x)}"
)

print(
    f"Raw file     : {raw_filename}"
)

print(
    f"CSV file     : {csv_filename}"
)


# ============================================================
# EXPORT / OPTIONAL PREVIEW
# ============================================================

if len(all_x) > 0:

    export_stride = max(1, int(PLY_EXPORT_STRIDE))
    x = np.asarray(all_x, dtype=np.float32)[::export_stride]
    y = np.asarray(all_y, dtype=np.float32)[::export_stride]
    time_s = np.asarray(all_time, dtype=np.float32)[::export_stride]
    rssi = np.asarray(all_rssi, dtype=np.uint8)[::export_stride]

    save_binary_ply(
        ply_filename,
        x,
        y,
        time_s,
        rssi
    )

    print(
        f"Three.js PLY : {ply_filename} "
        f"({len(x)} points)"
    )

    if GENERATE_MATPLOTLIB_PREVIEW:
        import matplotlib.pyplot as plt

        fig = plt.figure(figsize=(12, 9))
        ax = fig.add_subplot(111, projection="3d")

        points = ax.scatter(
            x,
            y,
            time_s,
            c=rssi,
            s=1,
            cmap="viridis"
        )

        # The scanner stays at X=0, Y=0 while time advances along Z.
        ax.plot(
            [0, 0],
            [0, 0],
            [0, max(elapsed, 1e-9)],
            color="red",
            linewidth=1,
            label="Scanner"
        )

        ax.set_xlabel("X (m)")
        ax.set_ylabel("Y (m)")
        ax.set_zlabel("Time (s)")

        # Preserve the original X/Y scan-plane proportions.  The time
        # dimension is kept readable even when its range differs greatly.
        x_range = max(float(np.ptp(x)), 1e-9)
        y_range = max(float(np.ptp(y)), 1e-9)
        xy_range = max(x_range, y_range)
        ax.set_box_aspect((xy_range, xy_range, xy_range * 0.8))

        ax.set_title(
            f"SICK microScan3 - {scan_count} scans"
        )

        ax.legend()
        fig.colorbar(points, ax=ax, pad=0.1, label="RSSI")
        fig.tight_layout()

        fig.savefig(
            png_filename,
            dpi=200,
            bbox_inches="tight"
        )

        print(
            f"PNG preview  : {png_filename}"
        )

        plt.show()

else:

    print(
        "No valid measurement points decoded."
    )
